### ISSUE TITLE
docker-compose fails to create network names

### ISSUE THREAD

**Issue by rcruicks** [alessfg/docker-ethercis#1]
can you add a links subsection to docker-compose.yml in the app: section to establish a hostname link to the postgres server?
       links:
    - postgres

I'm pointing docker at the IBM Bluemix environment, and it seems to need specific links

**Comment by alessfg** [comment]
Container links are deprecated. The docker-compose.yml uses the default network bridge to connect the application container to the postgres container. 

The issue probably lies in the IBM Bluemix environment already using the default network bridge. I will update the docker-compose.yml to use a different network in the next couple of days.

**Comment by rcruicks** [comment]
good point! 
it may be an issue in the docker-compose support on Bluemix - there is some doubt as to whether version 2 is fully supported.
without the links: section, the app server had no host alias for the postgres machine so was unable to connect to the database. 
I'll dig into the compose support some more -
